# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d261404b54feddc046f94881bb7df6ad60f0825475079ad100dfc2fdeaf556e52459e410748c5f67e8cd2f9d5f45e689480dd801f2f1036433cf6c822afeaf1

test:
  secret_key_base: b65d256d82094537aa7840db0d97548c552e126e5940483b4ad4917d249496e09298b32d6c57a4edf11df1cf26724e195d25f29cb3653ae18357c3db6dd4aea6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
